### ISSUE TITLE
No ARM image built

### ISSUE THREAD

**Issue by c00ldude1oo** [getlago/lago-gotenberg#2]
Please add builds for arm. The official [image](https://hub.docker.com/r/gotenberg/gotenberg/tags?name=latest) supports it. as did your last version.

also is repo dead? no commits related to last release on dockerhub

**Comment by jdenquin** [comment]
@c00ldude1oo I'll update to the last version and build for ARM too!

**Comment by jdenquin** [comment]
arm versions are up for `7.10`  and `8` on dockerhub

**Comment by c00ldude1oo** [comment]
Thanks
